## Preprocessing

In [2]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf

#  Import and read the charity_data.csv.
import pandas as pd
application_df = pd.read_csv("https://static.bc-edx.com/data/dl-1-2/m21/lms/starter/charity_data.csv")
application_df.head()

WARNING:tensorflow:From c:\Users\Joyjo\anaconda3\Lib\site-packages\keras\src\losses.py:2976: The name tf.losses.sparse_softmax_cross_entropy is deprecated. Please use tf.compat.v1.losses.sparse_softmax_cross_entropy instead.

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [3]:
# Drop the non-beneficial ID columns, 'EIN' and 'NAME'.
application_df = application_df.drop(columns=['EIN','USE_CASE','NAME','ORGANIZATION','EIN','SPECIAL_CONSIDERATIONS','STATUS'])
# Display dropped columns in dataframe
application_df.head()

,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,INCOME_AMT,ASK_AMT,IS_SUCCESSFUL
0,T10,Independent,C1000,0,5000,1
1,T3,Independent,C2000,1-9999,108590,1
2,T5,CompanySponsored,C3000,0,5000,0
3,T3,CompanySponsored,C2000,10000-24999,6692,1
4,T3,Independent,C1000,100000-499999,142590,1

In [4]:
# Determine the number of unique values in each column.
unique_values_count = application_df.nunique()
#display unique values in column
print(unique_values_count)

APPLICATION_TYPE      17
AFFILIATION            6
CLASSIFICATION        71
INCOME_AMT             9
ASK_AMT             8747
IS_SUCCESSFUL          2
dtype: int64

In [5]:
# Look at APPLICATION_TYPE value counts for binning
application_type_counts = application_df['APPLICATION_TYPE'].value_counts()
#Display value counts
print(application_type_counts)

APPLICATION_TYPE
T3     27037
T4      1542
T6      1216
T5      1173
T19     1065
T8       737
T7       725
T10      528
T9       156
T13       66
T12       27
T2        16
T25        3
T14        3
T29        2
T15        2
T17        1
Name: count, dtype: int64

In [6]:
# Choose a cutoff value and create a list of application types to be replaced
# use the variable name `application_types_to_replace`

cutoff_value = 500
application_type_counts = application_df['APPLICATION_TYPE'].value_counts()
application_types_to_replace = application_type_counts[application_type_counts < cutoff_value].index.tolist()

# Replace in dataframe
for app in application_types_to_replace:
    application_df['APPLICATION_TYPE'] = application_df['APPLICATION_TYPE'].replace(app,"Other")

# Check to make sure binning was successful
application_df['APPLICATION_TYPE'].value_counts()

APPLICATION_TYPE
T3       27037
T4        1542
T6        1216
T5        1173
T19       1065
T8         737
T7         725
T10        528
Other      276
Name: count, dtype: int64

In [7]:
# Look at CLASSIFICATION value counts for binning
classification_counts = application_df['CLASSIFICATION'].value_counts()

#display classification counts
print(classification_counts)

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
         ...
C4120        1
C8210        1
C2561        1
C4500        1
C2150        1
Name: count, Length: 71, dtype: int64

In [8]:
# You may find it helpful to look at CLASSIFICATION value counts >1
classification_counts_filtered = classification_counts[classification_counts > 1]
#display classification value counts
print(classification_counts_filtered)

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
C2800       95
C7100       75
C1300       58
C1280       50
C1230       36
C1400       34
C7200       32
C2300       32
C1240       30
C8000       20
C7120       18
C1500       16
C1800       15
C6000       15
C1250       14
C8200       11
C1238       10
C1278       10
C1235        9
C1237        9
C7210        7
C2400        6
C1720        6
C4100        6
C1257        5
C1600        5
C1260        3
C2710        3
C0           3
C3200        2
C1234        2
C1246        2
C1267        2
C1256        2
Name: count, dtype: int64

In [9]:
# Choose a cutoff value and create a list of classifications to be replaced
# use the variable name `classifications_to_replace`
cutoff_value = 800
classifications_to_replace = classification_counts[classification_counts < cutoff_value].index.tolist()
# Replace in dataframe
for cls in classifications_to_replace:
    application_df['CLASSIFICATION'] = application_df['CLASSIFICATION'].replace(cls,"Other")

# Check to make sure binning was successful
application_df['CLASSIFICATION'].value_counts()

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
Other     2261
C3000     1918
C2100     1883
Name: count, dtype: int64

In [10]:
# Convert categorical data to numeric with `pd.get_dummies`
application_df = pd.get_dummies(application_df)

#display converted data
print(application_df.head())

   ASK_AMT  IS_SUCCESSFUL  APPLICATION_TYPE_Other  APPLICATION_TYPE_T10  \
0     5000              1                   False                  True
1   108590              1                   False                 False
2     5000              0                   False                 False
3     6692              1                   False                 False
4   142590              1                   False                 False

   APPLICATION_TYPE_T19  APPLICATION_TYPE_T3  APPLICATION_TYPE_T4  \
0                 False                False                False
1                 False                 True                False
2                 False                False                False
3                 False                 True                False
4                 False                 True                False

   APPLICATION_TYPE_T5  APPLICATION_TYPE_T6  APPLICATION_TYPE_T7  ...  \
0                False                False                False  ...
1                False                False                False  ...
2                 True                False                False  ...
3                False                False                False  ...
4                False                False                False  ...

   CLASSIFICATION_Other  INCOME_AMT_0  INCOME_AMT_1-9999  \
0                 False          True              False
1                 False         False               True
2                 False          True              False
3                 False         False              False
4                 False         False              False

   INCOME_AMT_10000-24999  INCOME_AMT_100000-499999  INCOME_AMT_10M-50M  \
0                   False                     False               False
1                   False                     False               False
2                   False                     False               False
3                    True                     False               False
4                   False                      True               False

   INCOME_AMT_1M-5M  INCOME_AMT_25000-99999  INCOME_AMT_50M+  \
0             False                   False            False
1             False                   False            False
2             False                   False            False
3             False                   False            False
4             False                   False            False

   INCOME_AMT_5M-10M
0              False
1              False
2              False
3              False
4              False

[5 rows x 32 columns]

In [11]:
# Split our preprocessed data into our features and target arrays
y = application_df['IS_SUCCESSFUL'].values
X = application_df.drop(['IS_SUCCESSFUL'], axis=1).values

# Split the preprocessed data into a training and testing dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=78)

In [12]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

## Compile, Train and Evaluate the Model

In [13]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
number_input_features = len(X_train[0])
hidden_nodes_layer1 =  50
hidden_nodes_layer2 = 30

nn_model = tf.keras.models.Sequential()

# First hidden layer
nn_model.add(
    tf.keras.layers.Dense(units=hidden_nodes_layer1, input_dim=number_input_features, activation="relu")
)

# Second hidden layer
nn_model.add(tf.keras.layers.Dense(units=hidden_nodes_layer2, activation="relu"))



# Output layer
nn_model.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))

# Check the structure of the model
nn_model.summary()

WARNING:tensorflow:From c:\Users\Joyjo\anaconda3\Lib\site-packages\keras\src\backend.py:873: The name tf.get_default_graph is deprecated. Please use tf.compat.v1.get_default_graph instead.

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 50)                1600

 dense_1 (Dense)             (None, 30)                1530

 dense_2 (Dense)             (None, 1)                 31

=================================================================
Total params: 3161 (12.35 KB)
Trainable params: 3161 (12.35 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [14]:
# Compile the model
nn_model.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

WARNING:tensorflow:From c:\Users\Joyjo\anaconda3\Lib\site-packages\keras\src\optimizers\__init__.py:309: The name tf.train.Optimizer is deprecated. Please use tf.compat.v1.train.Optimizer instead.

In [15]:
# Train the model
fit_model = nn_model.fit(X_train_scaled, y_train, epochs=12)

Epoch 1/12
WARNING:tensorflow:From c:\Users\Joyjo\anaconda3\Lib\site-packages\keras\src\utils\tf_utils.py:492: The name tf.ragged.RaggedTensorValue is deprecated. Please use tf.compat.v1.ragged.RaggedTensorValue instead.

WARNING:tensorflow:From c:\Users\Joyjo\anaconda3\Lib\site-packages\keras\src\engine\base_layer_utils.py:384: The name tf.executing_eagerly_outside_functions is deprecated. Please use tf.compat.v1.executing_eagerly_outside_functions instead.

804/804 [==============================] - 3s 2ms/step - loss: 0.5789 - accuracy: 0.7168
Epoch 2/12
804/804 [==============================] - 2s 2ms/step - loss: 0.5663 - accuracy: 0.7259
Epoch 3/12
804/804 [==============================] - 2s 2ms/step - loss: 0.5650 - accuracy: 0.7262
Epoch 4/12
804/804 [==============================] - 2s 2ms/step - loss: 0.5635 - accuracy: 0.7269
Epoch 5/12
804/804 [==============================] - 2s 2ms/step - loss: 0.5631 - accuracy: 0.7278
Epoch 6/12
804/804 [==============================] - 2s 2ms/step - loss: 0.5625 - accuracy: 0.7271
Epoch 7/12
804/804 [==============================] - 2s 2ms/step - loss: 0.5621 - accuracy: 0.7279
Epoch 8/12
804/804 [==============================] - 2s 2ms/step - loss: 0.5618 - accuracy: 0.7276
Epoch 9/12
804/804 [==============================] - 2s 2ms/step - loss: 0.5615 - accuracy: 0.7284
Epoch 10/12
804/804 [==============================] - 2s 2ms/step - loss: 0.5617 - accuracy: 0.7287
Epoch 11/12
804/804 [==============================] - 2s 2ms/step - loss: 0.5608 - accuracy: 0.7293
Epoch 12/12
804/804 [==============================] - 2s 2ms/step - loss: 0.5609 - accuracy: 0.7286

In [16]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn_model.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 1s - loss: 0.5658 - accuracy: 0.7230 - 597ms/epoch - 2ms/step
Loss: 0.5657821297645569, Accuracy: 0.7230320572853088

In [17]:
import tensorflow.keras as keras

In [18]:
# Export our model to HDF5 file
# path to save file
model_filepath = "AlphabetSoupCharity_Optimization.h5"

# Save the model to HDF5 file
nn_model.save(model_filepath)

# Print a message indicating that the model has been saved
print("Model saved to: {model_filepath}")

Model saved to: {model_filepath}

c:\Users\Joyjo\anaconda3\Lib\site-packages\keras\src\engine\training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(